
name: My First CI Pipeline

on: [push]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Run Linter
        run: |
          echo "Запускаю проверку синтаксиса..."
          echo "Ошибок нет! Код идеален."

      # НОВЫЙ ШАГ: Авторизация в Docker Hub
      - name: Login to Docker Hub
        # Здесь мы достаем спрятанные пароли через спец. синтаксис GitHub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      # ОБНОВЛЕННЫЙ ШАГ: Сборка и отправка
      - name: Build and Push Docker Image
        run: |
          cd 03-docker
          # Собираем образ с правильным тегом (не забудь поменять логин!)
          docker build -t joraa/tiny-app:latest .
          # Отправляем в реестр
          docker push joraa/tiny-app:latest
